theme: jekyll-theme-midnight
title: MBB5546's Homepage
description: Inside the Mind of a Junior Penetration Tester

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

